name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Sett opp Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer avhengigheter
        run: npm install

      - name: Kjør tester
        run: npm test